### PR TITLE
rapid_msgs: remove non-ascii characters

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This is for ros-industrial/abb_robot_driver#17.

**Comment by gavanderhoorn** [comment]
Seems this is at least needed on some systems, and avoiding unicode in ROS `.msg`s is a good thing to do in any case.

@jontje: could you take a look?

**Review by jontje — APPROVED** [review]
Looks good to me

**Comment by gavanderhoorn** [comment]
Thanks.

**Pull request merged**
